### ISSUE TITLE
Tag Implementation Ideas

### ISSUE THREAD

**Issue by jeffsmithdev** [jeffsmithdev/statika#3]

**Comment by jeffsmithdev** [comment]
Sorry for the delay.  I added both types of tags.  It's not pretty for the moment.  2 examples are live here: 

https://www.statika.app/
https://www.code0x378.com/

In addition to tags there are numerous minor changes. You now need to pass a `-d` flag to specify the project dir as in:

`statika -d examples/simple.com -b`

Let me know any questions or issue.  Thanks.

**Comment by tyeeman** [comment]
Thanks Jeff! Much appreciated! I will try it out now.

**Comment by tyeeman** [comment]
Update - I built the exe and ran the manual build command of ```statika examples/simple.com -b``` and got an error - 

```
g:\Statica>statika examples/simple.com -b
2021/11/01 18:05:18 open .env: The system cannot find the file specified.
```

Give it a try at your end.

**Comment by tyeeman** [comment]
OK, looks great. I'm getting error in statika.app site with all the site png images. They seem to be blank. Please check.

**Comment by jeffsmithdev** [comment]
Oops. That is probably because I moved all the images (and maybe other assets) to something called git LFS which is better for binary storage.  Normally you do this with a new repo but I forgot.  Sorry.  Basically, there a re 2 options: 1) just nuke and clone repo again and you should get them or 2) you can try `git lfs fetch --all` from the command line in the main statika dir and that (should) pull down the binary images to your local repo.  Right now the blank files are probably just text files with info that points to the missing images.

**Comment by tyeeman** [comment]
Thanks Jeff. I've got distracted with other things lately but I'll get back to Statika soon. One question I did have was about those blocks on some of the pages using (I think) uuid values. How does that work?

**Comment by jeffsmithdev** [comment]
No problem.  I was busy with work too.  I just came back to statika tonight to add something.  The UUID's are not being used in this statika at the moment and are not required.  I previously used the uuid to match the pages to another database.  The UUID linked to the database entry with additional meta data like creation date, whether a page is reused on another site, related pages and so on. I just left them in for now.
